FROM centos:latest
MAINTAINER byl0561@gmail.com
COPY autoLoginWLT.sh /autoLoginWLT/autoLoginWLT.sh
WORKDIR /autoLoginWLT
ENV name byl0561
ENV pass 193218
ENTRYPOINT ["/bin/bash", "/autoLoginWLT/autoLoginWLT.sh"]
